{
 "title": "Weather",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "out_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heat Index",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "heat_index" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Wind Chill",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wind_chill" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Dew Point",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "dew_point" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Dir",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wind_dir" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "out_humid" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "in" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "weather",
     "query": "SELECT \"rain_delta\" FROM \"weather\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "rain_delta" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 15, "w": 20, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Out Temp",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wind Chill",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT min(\"wind_chill\") FROM \"autogen\".\"weather\" WHERE $timeFilter GROUP BY time(10m)",
     "select": [
      [
       { "params": [ "wind_chill" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heat Index",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT min(\"wind_chill\") FROM \"autogen\".\"weather\" WHERE $timeFilter GROUP BY time(10m)",
     "select": [
      [
       { "params": [ "heat_index" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Dew Point",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "dew_point" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Wind Speed",
     "measurement": "weather",
     "query": "SELECT \"out_temp\" FROM \"autogen\".\"weather\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "out_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Chill",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Wind Speed",
     "measurement": "weather",
     "query": "SELECT \"out_temp\" FROM \"autogen\".\"weather\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "wind_chill" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Heat Index",
     "measurement": "weather",
     "query": "SELECT \"out_temp\" FROM \"autogen\".\"weather\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "heat_index" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wind Speed",
     "measurement": "weather",
     "query": "SELECT \"out_temp\" FROM \"autogen\".\"weather\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 22, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "alias": "Wind Speed",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "in" } },
   "yaxes": [
    { "format": "in" }
   ],
   "targets": [
    {
     "alias": "Rain",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain_delta" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "out_humid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wind Speed",
     "measurement": "weather",
     "query": "SELECT \"out_temp\" FROM \"autogen\".\"weather\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "out_humid" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}